### PR TITLE
Adding a preview/installer script and updating the README with info

### PR DESCRIPTION
**Pull request by shearn89**
I've added a simple preview script that rattles through the themes, as the screenshot (although pretty) didn't name them - trying to pick one was pot luck to start with! The script also sets up the assets directory and runs conky before the preview.

### CODE REVIEW

**Comment by zagortenay333** [comment]
Nice. Although, it would much nicer if the user could navigate back and forth and then choose the desired theme. Also, looping through the modes and the themes would be nice.

If you're too lazy to do that I'll merge this and add it myself later if I'm not too lazy.

**Comment by shearn89** [comment]
Ah, good shout! I'll see what I can do. Might end up not being in bash, but that shouldn't be a problem!

**Comment by zagortenay333** [comment]
Keep it in bash please. I don't want any python scripts or other stuff here.

**Comment by shearn89** [comment]
Done! All interactive with install (for API key settings etc), as well as backup/revert config.

**Comment by zagortenay333** [comment]
Oh nice. Sorry can't review now, will do soon. Thanks! :smile:

**Comment by zagortenay333** [comment]
Just tested. The vim navigation is absolutely brilliant! :+1:

**Comment by shearn89** [comment]
Cheers! :beers:

Turns out arrow keys are tricky to read in bash, so I figured vim-style would be simpler!

**Pull request merged**
